### ISSUE TITLE
mock 图表 模拟接口数据时会终止程序运行

### ISSUE THREAD

**Issue by wmx-us** [DomeSy/Ant-Design-Pro-V5#3]
![image](https://user-images.githubusercontent.com/68103050/184080759-f764a97c-22c6-4a4d-9644-b726c00bdc5f.png)

![image](https://user-images.githubusercontent.com/68103050/184080985-a6fdf322-ae61-48b9-b3c3-5a560ce1f088.png)

应该 return 接口返回值 ，望 作者 及时修复~

**Comment by DomeSy** [comment]
好久都没更新过了～可以关注下我的掘金 https://juejin.cn/user/703321119406919 ，里面有更多React的文章，相信能更好的帮助你～
